package main

import (
	// Register connectors
	_ "github.com/jxo-me/netx/x/connector/direct"
	_ "github.com/jxo-me/netx/x/connector/forward"
	_ "github.com/jxo-me/netx/x/connector/http"
	_ "github.com/jxo-me/netx/x/connector/http2"
	_ "github.com/jxo-me/netx/x/connector/relay"
	_ "github.com/jxo-me/netx/x/connector/sni"
	_ "github.com/jxo-me/netx/x/connector/socks/v4"
	_ "github.com/jxo-me/netx/x/connector/socks/v5"
	_ "github.com/jxo-me/netx/x/connector/ss"
	_ "github.com/jxo-me/netx/x/connector/ss/udp"
	_ "github.com/jxo-me/netx/x/connector/sshd"

	// Register dialers
	_ "github.com/jxo-me/netx/x/dialer/direct"
	_ "github.com/jxo-me/netx/x/dialer/dtls"
	_ "github.com/jxo-me/netx/x/dialer/ftcp"
	_ "github.com/jxo-me/netx/x/dialer/grpc"
	_ "github.com/jxo-me/netx/x/dialer/http2"
	_ "github.com/jxo-me/netx/x/dialer/http2/h2"
	_ "github.com/jxo-me/netx/x/dialer/http3"
	_ "github.com/jxo-me/netx/x/dialer/icmp"
	_ "github.com/jxo-me/netx/x/dialer/kcp"
	_ "github.com/jxo-me/netx/x/dialer/mtls"
	_ "github.com/jxo-me/netx/x/dialer/mws"
	_ "github.com/jxo-me/netx/x/dialer/obfs/http"
	_ "github.com/jxo-me/netx/x/dialer/obfs/tls"
	_ "github.com/jxo-me/netx/x/dialer/pht"
	_ "github.com/jxo-me/netx/x/dialer/quic"
	_ "github.com/jxo-me/netx/x/dialer/ssh"
	_ "github.com/jxo-me/netx/x/dialer/sshd"
	_ "github.com/jxo-me/netx/x/dialer/tcp"
	_ "github.com/jxo-me/netx/x/dialer/tls"
	_ "github.com/jxo-me/netx/x/dialer/udp"
	_ "github.com/jxo-me/netx/x/dialer/ws"

	// Register handlers
	_ "github.com/jxo-me/netx/x/handler/auto"
	_ "github.com/jxo-me/netx/x/handler/dns"
	_ "github.com/jxo-me/netx/x/handler/forward/local"
	_ "github.com/jxo-me/netx/x/handler/forward/remote"
	_ "github.com/jxo-me/netx/x/handler/http"
	_ "github.com/jxo-me/netx/x/handler/http2"
	_ "github.com/jxo-me/netx/x/handler/http3"
	_ "github.com/jxo-me/netx/x/handler/redirect/tcp"
	_ "github.com/jxo-me/netx/x/handler/redirect/udp"
	_ "github.com/jxo-me/netx/x/handler/relay"
	_ "github.com/jxo-me/netx/x/handler/sni"
	_ "github.com/jxo-me/netx/x/handler/socks/v4"
	_ "github.com/jxo-me/netx/x/handler/socks/v5"
	_ "github.com/jxo-me/netx/x/handler/ss"
	_ "github.com/jxo-me/netx/x/handler/ss/udp"
	_ "github.com/jxo-me/netx/x/handler/sshd"
	_ "github.com/jxo-me/netx/x/handler/tap"
	_ "github.com/jxo-me/netx/x/handler/tun"

	// Register listeners
	_ "github.com/jxo-me/netx/x/listener/dns"
	_ "github.com/jxo-me/netx/x/listener/dtls"
	_ "github.com/jxo-me/netx/x/listener/ftcp"
	_ "github.com/jxo-me/netx/x/listener/grpc"
	_ "github.com/jxo-me/netx/x/listener/http2"
	_ "github.com/jxo-me/netx/x/listener/http2/h2"
	_ "github.com/jxo-me/netx/x/listener/http3"
	_ "github.com/jxo-me/netx/x/listener/http3/h3"
	_ "github.com/jxo-me/netx/x/listener/icmp"
	_ "github.com/jxo-me/netx/x/listener/kcp"
	_ "github.com/jxo-me/netx/x/listener/mtls"
	_ "github.com/jxo-me/netx/x/listener/mws"
	_ "github.com/jxo-me/netx/x/listener/obfs/http"
	_ "github.com/jxo-me/netx/x/listener/obfs/tls"
	_ "github.com/jxo-me/netx/x/listener/pht"
	_ "github.com/jxo-me/netx/x/listener/quic"
	_ "github.com/jxo-me/netx/x/listener/redirect/tcp"
	_ "github.com/jxo-me/netx/x/listener/redirect/udp"
	_ "github.com/jxo-me/netx/x/listener/rtcp"
	_ "github.com/jxo-me/netx/x/listener/rudp"
	_ "github.com/jxo-me/netx/x/listener/ssh"
	_ "github.com/jxo-me/netx/x/listener/sshd"
	_ "github.com/jxo-me/netx/x/listener/tap"
	_ "github.com/jxo-me/netx/x/listener/tcp"
	_ "github.com/jxo-me/netx/x/listener/tls"
	_ "github.com/jxo-me/netx/x/listener/tun"
	_ "github.com/jxo-me/netx/x/listener/udp"
	_ "github.com/jxo-me/netx/x/listener/ws"
)
