package consts

const (
	// Connector
	Direct  = "direct"
	Virtual = "virtual"
	Forward = "forward"
	Http    = "http"
	Http2   = "http2"
	Relay   = "relay"
	Serial  = "serial"
	Sni     = "sni"
	Socks4  = "socks4"
	Socks4a = "socks4a"
	Socks5  = "socks5"
	Socks   = "socks"
	Ss      = "ss"
	Ssu     = "ssu"
	Sshd    = "sshd"
	Unix    = "unix"
	// dialer
	Dtls  = "dtls"
	Ftcp  = "ftcp"
	Grpc  = "grpc"
	H2    = "h2"
	H2c   = "h2c"
	Http3 = "http3"
	H3    = "h3"
	Icmp  = "icmp"
	Kcp   = "kcp"
	Mtls  = "mtls"
	Mws   = "mws"
	Mwss  = "mwss"
	Ohttp = "ohttp"
	Otls  = "otls"
	Pht   = "pht"
	Phts  = "phts"
	Quic  = "quic"
	Ssh   = "ssh"
	Tcp   = "tcp"
	Tls   = "tls"
	Udp   = "udp"
	Ws    = "ws"
	Wss   = "wss"

	// Auto Handler
	Auto     = "auto"
	Dns      = "dns"
	Rtcp     = "rtcp"
	Rudp     = "rudp"
	Red      = "red"
	Redir    = "redir"
	Redirect = "redirect"
	Redu     = "redu"
	Tap      = "tap"
	Tun      = "tun"

	//listener

)
