package consts

const (
	// Connector
	Direct  = "direct"
	Virtual = "virtual"
	Forward = "forward"
	Http    = "http"
	Http2   = "http2"
	Relay   = "relay"
	Router  = "router"
	Serial  = "serial"
	Sni     = "sni"
	Socks4  = "socks4"
	Socks4a = "socks4a"
	Socks5  = "socks5"
	Socks   = "socks"
	Ss      = "ss"
	Ssu     = "ssu"
	Sshd    = "sshd"
	Unix    = "unix"
	// dialer
	Dtls    = "dtls"
	Ftcp    = "ftcp"
	Grpc    = "grpc"
	H2      = "h2"
	H2c     = "h2c"
	Http3   = "http3"
	Metrics = "metrics"
	H3      = "h3"
	Wt      = "wt"
	Icmp    = "icmp"
	Kcp     = "kcp"
	Mtcp    = "mtcp"
	Mtls    = "mtls"
	Mws     = "mws"
	Mwss    = "mwss"
	Ohttp   = "ohttp"
	Otls    = "otls"
	Pht     = "pht"
	Phts    = "phts"
	Quic    = "quic"
	Ssh     = "ssh"
	Tcp     = "tcp"
	Tunnel  = "tunnel"
	Tls     = "tls"
	Udp     = "udp"
	Wg      = "wg"
	Ws      = "ws"
	Wss     = "wss"

	// Auto Handler
	Auto     = "auto"
	Api      = "api"
	Dns      = "dns"
	File     = "file"
	Rtcp     = "rtcp"
	Rudp     = "rudp"
	Red      = "red"
	Redir    = "redir"
	Redirect = "redirect"
	Redu     = "redu"
	Tap      = "tap"
	Tun      = "tun"

	//listener

)
